# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 24 Sep 2025 11:09:25 +0200
*	@admin 255
*	@ALL	0
*	@user	1
start	@ALL	1
wiki:*	@ALL	1
