<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: vd
 * Date: Tue, 28 Oct 2025 13:48:32 +0100
 */

$conf['title'] = 'Uniwiki';
$conf['template'] = 'mikio';
$conf['license'] = 'cc-by-sa';
$conf['camelcase'] = 1;
$conf['hidepages'] = '.*recursos.*';
$conf['useacl'] = 1;
$conf['autopasswd'] = 0;
$conf['superuser'] = '@admin';
$conf['mailfrom'] = 'htalearner@gmail.com';
$conf['mailprefix'] = '[Uniwiki] ';
$conf['plugin']['gallery']['options'] = 'cache,crop,lightbox';
$conf['plugin']['tplmod']['sitetools'] = 'Recent Changes,Media Manager,Sitemap';
$conf['plugin']['tplmod']['pagetools'] = 'Backlinks,Subscribe,Revert';
$conf['plugin']['tplmod']['logos'] = 'logo.png, uniwiki.ico';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
$conf['tpl']['mikio']['showLightDark'] = '1';
$conf['tpl']['mikio']['autoLightDark'] = '1';
$conf['tpl']['mikio']['defaultDark'] = '1';
$conf['tpl']['mikio']['stickyNavbar'] = '1';
$conf['tpl']['mikio']['stickyHeader'] = '1';
$conf['mailsend'] = 'smtp';
$conf['smtp_host'] = 'smtp.gmail.com';
$conf['smtp_port'] = '587';
$conf['smtp_user'] = 'htalearner@gmail.com';
$conf['smtp_pass'] = 'gldn euat uyih dbnx';
$conf['smtp_secure'] = 'tls';
