# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 24 Sep 2025 11:09:25 +0200
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

vd:$2a$12$aLCIIdyDCbxKKX7jOJGxfuz8VrhkSzgYrAzA5.jk9JB5D/lcAu8Wa:Vritik:vritikvalabdas@gmail.com:admin,user
admin:$2a$12$WuYDUe0ElPxOR5dhH9/BXOmXnxh4Zl4KMOuQJQJAW7C.wXcVsPSRG:Administrator:admin@localhost:admin,user
htajnr:$2a$12$nXDE1FNgIog21U0tav51summ0oXGTf7wtY6b98u7EProxxm7FfjCK:Hélder:htalearner@gmail.com:admin,user
jnrlite:$2y$10$sqFAAD32RVSKPVWSkPOC4.EtaA.R0GbD/WLD5ahds3bTzV2JI99VS:Junior:contadedesconfianca@gmail.com:user
habibi:$2y$10$QlIeUylWVnK1Rk3ejryOfuzk2SAGI0FSuL.5MdPwtK4LCThADFNgW:habibi:habibi@gmail.com:user
manuelito:$2y$10$f9vvEEhcFW4PSlTJSYIDWuhRExq4jv8mqrhKEnkqTItUcmZmyeShK:Manuelito:manuelito@local.com:user,admin
